import type { Metadata } from 'next';

import { inter, poppinsSans } from '@/lib/constants';

import '@/styles/globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${poppinsSans.variable} ${inter.variable} antialiased`}>{children}</body>
		</html>
	);
}
